final_project2/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sales
  resources :categories
  resources :products
  resources :buyers
  resources :sellers
  resources :admins
  get 'mypurchases', to: 'buyers#purchases'
  get 'myproducts', to: 'sales#own'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/register', to: 'welcome#register'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: "welcome#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final_project2/app/views/layouts/_navigation.html.erb
<div class="imgbar"> 
    <img class="logo" src="/logo/MIS21_logo.png">
</div>

<br>
<br>
<br>
<br>
<br>

<div class="navbar1" class="navbar2" class="navbar3"> 
    <% if buyer_logged_in? && current_user.admin? %>
        <h2 class="navhead" style="text-align: center;">Administrator Page</h2>
        <ul style="text-align: center;">
            <%= link_to "Home", root_path,class:'button'%>
            <%= link_to "About", welcome_about_path, class:'button'%>
            <%= link_to "Categories", categories_path,class:'button'%>
            <%= link_to "Products", products_path,class:'button'%>
            <%= link_to "Sales", sales_path,class:'button'%>
            <%= link_to "Buyers", buyers_path,class:'button'%>
            <%= link_to "Sellers", sellers_path,class:'button'%>
            <%= link_to "Log Out", logout_path, method: :delete,class:'button' %>
        </ul>
    <% elsif buyer_logged_in? %>
        <h2 class="navhead" style="text-align: center;">Hello Buyer, <%= current_user.first_name%>!</h2>
        <ul style="text-align: center;">
            <%= link_to "Home", root_path, class:'button'%>
            <%= link_to "About", welcome_about_path, class:'button'%>
            <%= link_to "My Purchases", mypurchases_path, class:'button'%>
            <%= link_to "Log Out", logout_path, method: :delete, class:'button' %>
        </ul>
    <% elsif seller_logged_in? && current_user.admin? %>
        <h2 class="navhead" style="text-align: center;">Administrator Page</h2>
        <ul style="text-align: center;">
            <%= link_to "Home", root_path, class:'button'%>
            <%= link_to "About", welcome_about_path, class:'button'%>
            <%= link_to "Categories", categories_path, class:'button'%>
            <%= link_to "Products", products_path, class:'button'%>
            <%= link_to "Sales", sales_path, class:'button'%>
            <%= link_to "Buyers", buyers_path, class:'button'%>
            <%= link_to "Sellers", sellers_path, class:'button'%>
            <%= link_to "Log Out", logout_path, method: :delete, class:'button' %>
        </ul>
    <% elsif seller_logged_in? %>
        <h2 class="navhead" style="text-align: center;">Hello Seller, <%= current_user.first_name%>!</h2>
        <ul style="text-align: center;">
            <%= link_to "Home", root_path , class:'button'%>
            <%= link_to "About", welcome_about_path, class:'button'%>
            <%= link_to "Products", products_path, class:'button'%>
            <%= link_to "My Products", myproducts_path, class:'button'%>
            <%= link_to "Sales", sales_path, class:'button'%>
            <%= link_to "Log Out", logout_path, method: :delete, class:'button' %>
        </ul>
    <% else %>
        <ul style="text-align: center;">
            <%= link_to "Home", root_path, class:'button'%>
            <%= link_to "About", welcome_about_path, class:'button'%>
            <%= link_to "Register", welcome_register_path, class:'button'%>
            <%= link_to "Login", login_path, class:'button'%>
        </ul>
    <% end %>
</div>

final_project2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FinalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navigation' %>
    <%= yield %>

  </body>
</html>