final_project2/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sales
  resources :categories
  resources :products
  resources :buyers
  resources :sellers
  resources :admins
  get 'mypurchases', to: 'buyers#purchases'
  get 'myproducts', to: 'sales#own'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/register', to: 'welcome#register'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: "welcome#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final_project2/app/models/buyer.rb
class Buyer < ApplicationRecord
	has_many :sales
	before_save {self.email = email.downcase}
	validates :first_name,
		presence: true

	validates :last_name,
		presence: true

	validates :birthday,
		presence: true

	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email,
	presence: true,
	length: {maximum: 100},
	uniqueness: { case_sensitivity: false},
	format: {with: VALID_EMAIL_REGEX}
	has_secure_password
end

final_project2/app/controllers/buyers_controller.rb
class BuyersController < ApplicationController
  before_action :set_buyer, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:create, :new, :purchases, :show]
  before_action :require_buyer, only: [:purchases]
  # GET /buyers
  # GET /buyers.json
  def index
    @buyers = Buyer.all
  end

  def purchases
    @sales = Sale.all
  end

  # GET /buyers/1
  # GET /buyers/1.json
  def show
  end

  # GET /buyers/new
  def new
    @buyer = Buyer.new
  end

  # GET /buyers/1/edit
  def edit
  end

  # POST /buyers
  # POST /buyers.json
  def create
    @buyer = Buyer.new(buyer_params)

    respond_to do |format|
      if @buyer.save
        format.html { redirect_to @buyer, notice: 'Buyer was successfully created.' }
        format.json { render :show, status: :created, location: @buyer }
      else
        format.html { render :new }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /buyers/1
  # PATCH/PUT /buyers/1.json
  def update
    respond_to do |format|
      if @buyer.update(buyer_params)
        format.html { redirect_to @buyer, notice: 'Buyer was successfully updated.' }
        format.json { render :show, status: :ok, location: @buyer }
      else
        format.html { render :edit }
        format.json { render json: @buyer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buyers/1
  # DELETE /buyers/1.json
  def destroy
    @buyer.destroy
    respond_to do |format|
      format.html { redirect_to buyers_url, notice: 'Buyer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_buyer
      @buyer = Buyer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def buyer_params
      params.require(:buyer).permit(:email, :password, :first_name, :last_name, :sex, :birthday)
    end
end

final_project2/app/helpers/buyers_helper.rb
module BuyersHelper
end

final_project2/app/views/buyers/_form.html.erb
<%= form_with(model: buyer, local: true) do |form| %>
  <% if buyer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(buyer.errors.count, "error") %> prohibited this buyer from being saved:</h2>

      <ul>
      <% buyer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sign">
    <%= form.label :email, class:'text' %>
    <%= form.text_field :email %>
  </div>
  <br>

  <div class="sign">
    <%= form.label :password, class:'text' %>
    <%= form.password_field :password %>
  </div>
  <br>

  <div class="sign">
    <%= form.label :first_name, class:'text' %>
    <%= form.text_field :first_name %>
  </div>
  <br>

  <div class="sign">
    <%= form.label :last_name, class:'text' %>
    <%= form.text_field :last_name %>
  </div>
  <br>

  <div class="sign">
    <%= form.label :sex, class:'text' %>
    <%= form.select :sex, ['Male', 'Female'] %>
  </div>
  <br>

  <div class="sign">
    <%= form.label :birthday, class:'text' %>
    <%= form.date_select :birthday %>
  </div>
  <br>

  <div class="sign">
    <%= form.submit %>
  </div>
<% end %>

final_project2/app/views/buyers/edit.html.erb
<div class="sign">
	<h1 class="head">Editing Buyer</h1>
</div>


<%= render 'form', buyer: @buyer %>

<br>
<div class="sign">
	<%= link_to 'Show', @buyer, class:'button2' %> 
<%= link_to 'Back', buyers_path, class:'button2' %>
</div>

final_project2/app/views/buyers/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head" style="text-align: center;">Buyers</h1>


<table class="table">
  <thead class="th2">
    <tr>
      <th>Email</th>
      <th>Password</th>
      <th>First name</th>
      <th>Last name</th>
      <th>Sex</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buyers.each do |buyer| %>
      <tr>
        <td class="td"><%= buyer.email %></td>
        <td class="td"><%= buyer.password_digest %></td>
        <td class="td"><%= buyer.first_name %></td>
        <td class="td"><%= buyer.last_name %></td>
        <td class="td"><%= buyer.sex %></td>
        <td class="td"><%= buyer.birthday %></td>
        <td class="td"><%= link_to 'Show', buyer %></td>
        <td class="td"><%= link_to 'Edit', edit_buyer_path(buyer) %></td>
        <td class="td"><%= link_to 'Destroy', buyer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<br>
<div style="text-align: center;">
  <%= link_to 'New Buyer', new_buyer_path, class:'button2' %>
</div>

final_project2/app/views/buyers/new.html.erb
<div class="sign">
	<h1 class="head">New Buyer</h1>
</div>

<img class="edit" src="/new/airmax.jpg">
<%= render 'form', buyer: @buyer %>
<% if (seller_logged_in? && current_user.admin?) || (buyer_logged_in? && current_user.admin?) %>
<br>
<div class="sign">
	<%= link_to 'Back', buyers_path, class:'button2' %>
</div>

<%end%>

final_project2/app/views/buyers/purchases.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My Purchases</title>
</head>
<h1 class="head" style="text-align: center;">My Purchases</h1>
<body>
	

		<table class="table">
  			<thead class="th2">
  				<tr>
  					<th>Seller</th>
				    <th>Buyer</th>
				    <th>Product</th>
				    <th>Price</th>
				    <th>Remarks</th>
				    <th colspan="3"></th>
				</tr>
			</thead>

			<tbody >  
<% @sales.each do |sale| %>
<% if buyer_logged_in? && (current_user == sale.buyer) %>
				<tr class="td">
				    <td class="td"><%= sale.seller.first_name %> <%= sale.seller.last_name %></td>
					<% if !sale.buyer.nil?%>
					   	<td class="td"><%= sale.buyer.first_name %> <%= sale.buyer.last_name %></td>
					<% else %>
					    <td class="td">no buyer</td>
					<%end%>
					<td class="td"><%= sale.product.name %></td>
					<td class="td"><%= sale.price %></td>
					<td class="td"><%= sale.remarks %></td>
					<td class="td"><%= link_to 'Show', sale %></td>
				</tr>
				<% end %>
	<%end%>
  			</tbody>
  		</table>
		
</body>
</html>

final_project2/app/views/buyers/show.html.erb
<p id="notice" class="sign"><%= notice %></p>

<p class="sign">
  <strong class="text">Email:</strong>
  <%= @buyer.email %>
</p>

<p class="sign">
  <strong class="text">Password:</strong>
  <%= @buyer.password_digest %>
</p>

<p class="sign">
  <strong class="text">First name:</strong>
  <%= @buyer.first_name %>
</p>

<p class="sign">
  <strong class="text">Last name:</strong>
  <%= @buyer.last_name %>
</p>

<p class="sign">
  <strong class="text">Sex:</strong>
  <%= @buyer.sex %>
</p>

<p class="sign">
  <strong class="text">Birthday:</strong>
  <%= @buyer.birthday %>
</p>
<% if (seller_logged_in? || buyer_logged_in?) && current_user.admin?%>
<div style="text-align: center;">
  <%= link_to 'Edit', edit_buyer_path(@buyer), class:'button2' %> 
<%= link_to 'Back', buyers_path, class:'button2' %>
</div>
<% end %>