final_project2/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sales
  resources :categories
  resources :products
  resources :buyers
  resources :sellers
  resources :admins
  get 'mypurchases', to: 'buyers#purchases'
  get 'myproducts', to: 'sales#own'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/register', to: 'welcome#register'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: "welcome#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final_project2/app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	validates :name,
		presence: true
end

final_project2/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: [:show, :edit, :update, :destroy]
  before_action :require_admin
  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1
  # PATCH/PUT /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category.destroy
    respond_to do |format|
      format.html { redirect_to categories_url, notice: 'Category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def category_params
      params.require(:category).permit(:name)
    end
end

final_project2/app/helpers/categories_helper.rb
module CategoriesHelper
end

final_project2/app/views/categories/_form.html.erb
<%= form_with(model: category, local: true) do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul>
      <% category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="sign">
    <%= form.label :name, class:'text' %>
    <%= form.text_field :name  %>
  </div>

  <div class="sign">
    <%= form.submit %>
  </div>
<% end %>

final_project2/app/views/categories/edit.html.erb
<div class ="sign">
	<h1 class="head">Editing Category</h1>
</div>

<%= render 'form', category: @category %>
<br>
	<div class ="sign">
	<%= link_to 'Show', @category, class:'button2' %>
	<%= link_to 'Back', categories_path, class:'button2' %>
</div>

final_project2/app/views/categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head" style="text-align: center;">Categories</h1>

<table class="table">
  <thead class="th2" style="text-align: center;">
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
      <tr>
        <td class="td"><%= category.name %></td>
        <td class="td"><%= link_to 'Show', category %></td>
        <td class="td"><%= link_to 'Edit', edit_category_path(category) %></td>
        <td class="td"><%= link_to 'Destroy', category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<div style="text-align: center;">
<%= link_to 'New Category', new_category_path, class:'button2' %>
</div>

final_project2/app/views/categories/new.html.erb
<div class ="sign">
	<h1>New Category</h1>
</div>

<%= render 'form', category: @category %>
<br>
<div class = "sign">
<%= link_to 'Back', categories_path, class:'button2' %>
</div>

final_project2/app/views/categories/show.html.erb
<p id="notice"><%= notice %></p>

<p class = "sign">
  <strong class="text">Name:</strong>
  <%= @category.name %>
</p>

<div class ="sign">
	<%= link_to 'Edit', edit_category_path(@category), class:'button2' %> 
	<%= link_to 'Back', categories_path, class:'button2' %>
</div>