final_project2/config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'
  resources :sales
  resources :categories
  resources :products
  resources :buyers
  resources :sellers
  resources :admins
  get 'mypurchases', to: 'buyers#purchases'
  get 'myproducts', to: 'sales#own'
  get 'welcome/about', to: 'welcome#about'
  get 'welcome/register', to: 'welcome#register'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  root to: "welcome#home"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

final_project2/app/models/sale.rb
class Sale < ApplicationRecord
	belongs_to :seller
	belongs_to :buyer, optional: true
	belongs_to :product

	validates :price,
		presence: true
end

final_project2/app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action :set_sale, only: [:show, :edit, :update, :destroy]
  before_action :require_seller, except: [:show, :edit, :update]
  # GET /sales
  # GET /sales.json
  def index
    @sales = Sale.all
    @buyers = Buyer.all
    @products = Product.all
  end

  # GET /sales/1
  # GET /sales/1.json
  def show
  end

  # GET /sales/new
  def new
    @sale = Sale.new
    @products = Product.all
  end

  # GET /sales/1/edit
  def edit
    @products = Product.all
  end

  # POST /sales
  # POST /sales.json
  def create
    @sale = Sale.new(sale_params)
    @sale.seller_id = current_user.id
    @products = Product.all

    respond_to do |format|
      if @sale.save
        format.html { redirect_to @sale, notice: 'Sale was successfully created.' }
        format.json { render :show, status: :created, location: @sale }
      else
        format.html { render :new }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sales/1
  # PATCH/PUT /sales/1.json
  def update
    @sale = Sale.find(params[:id])
    @sale.buyer_id = current_user.id
    respond_to do |format|
      if @sale.update(sale_params)
        format.html { redirect_to @sale, notice: 'Sale was successfully updated.' }
        format.json { render :show, status: :ok, location: @sale }
      else
        format.html { render :edit }
        format.json { render json: @sale.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sales/1
  # DELETE /sales/1.json
  def destroy
    @sale.destroy
    respond_to do |format|
      format.html { redirect_to sales_url, notice: 'Sale was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def own
    @sales = Sale.all
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sale
      @sale = Sale.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sale_params
      params.require(:sale).permit(:seller_id, :buyer_id, :product_id, :price, :remarks)
    end
end

final_project2/app/helpers/sales_helper.rb
module SalesHelper
end

final_project2/app/views/sales/_form.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="sign">
   <h2 class="text">Product IDs:</h2>
</div>
 
  <table class="table">
  <thead class="th2">
    <tr>
      <th>ID</th>
      <th>Product</th>
      <th>Description</th>
      <th>Category</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |pro|%>
    <div>
      <tr>
        <td class="td"><%= pro.id%></td>
        <td class="td"><%= pro.name%></td>
        <td class="td"><%= pro.description%></td>
        <td class="td"><%= pro.category.name%></td>
        <td class = "td"><%= image_tag pro.avatar.url(:medium)%></td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>
  <br>

<!--   hides seller id and sets automatically -->
  <div class="sign">
    <% form.label :seller_id, class:'text' %>
    <% form.number_field :seller_id, :value => current_user.id %>
  </div>
<br>
  <div class="sign">
      <%= form.label :product_id, class:'text'%>
      <%= form.number_field :product_id, max: @products.count, min:1 %>
  </div>
<br>
  <div class="sign">
    <% form.label :buyer_id, class:'text'%>
    <% form.number_field :buyer_id, :value => nil %>
  </div>
<br>
  <div class="sign">
    <%= form.label :price, class:'text' %>
    <%= form.text_field :price %>
  </div>
<br>
  <div class="sign">
    <%= form.label :remarks, class:'text' %>
    <%= form.text_area :remarks %>
  </div>
<br>
  <div class="sign">
    <%= form.submit %>
  </div>
<% end %>

final_project2/app/views/sales/_formtwo.html.erb
<%= form_with(model: sale, local: true) do |form| %>
  <% if sale.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sale.errors.count, "error") %> prohibited this sale from being saved:</h2>

      <ul>
      <% sale.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="sign">
   <h2 class="text">Product IDs:</h2>
</div>
 
  <table class="table">
  <thead class="th2">
    <tr>
      <th>ID</th>
      <th>Product</th>
      <th>Description</th>
      <th>Category</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |pro|%>
    <div>
      <tr>
        <td class="td"><%= pro.id%></td>
        <td class="td"><%= pro.name%></td>
        <td class="td"><%= pro.description%></td>
        <td class="td"><%= pro.category.name%></td>
        <td class = "td"><%= image_tag pro.avatar.url(:medium)%></td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>
  <br>

<!--   hides seller id and sets automatically -->
  <div class="sign">
    <% form.label :seller_id, class:'text' %>
    <% form.number_field :seller_id, :value => current_user.id %>
  </div>
<br>
  <div class="sign">
    <% form.label :buyer_id, class:'text'%>
    <% form.number_field :buyer_id, :value => current_user.id %>
  </div>
<br>
  <div class="sign">
      <%= form.label :product_id, class:'text'%>
      <%= form.number_field :product_id, max: @products.count, min:1, :readonly => "readonly" %>
  </div>
<br>
  <div class="sign">
    <%= form.label :price, class:'text' %>
    <%= form.text_field :price, :readonly => "readonly" %>
  </div>
<br>
  <div class="sign">
    <%= form.label :remarks, class:'text' %>
    <%= form.text_area :remarks, :readonly => "readonly" %>
  </div>
<br>
  <div class="sign">
    <%= form.submit :BUY%>
  </div>

<% end %>

final_project2/app/views/sales/edit.html.erb
<div class="sign">
	<h1 class="head">Editing Sale</h1>
</div>

<% if seller_logged_in? && (current_user == @sale.seller) && !@sale.buyer_id.nil? %>
	<p>You cannot edit a sale that has already been purchased.</p>
<% elsif seller_logged_in? && (current_user == @sale.seller) %>
	<%= render 'form', sale: @sale %>
<% elsif buyer_logged_in? && @sale.buyer_id.nil?%>
	<%= render 'formtwo', sale: @sale %>
<% elsif buyer_logged_in? && !@sale.buyer_id.nil?%>
	<p class="text" style="text-align: center;">This item is no longer for sale.</p>
<% else %>
	<p class="text" style="text-align: center;">You can only edit your own sales!</p>
<% end %>

<% if !buyer_logged_in? %>
<br>
<div class="sign">
	<%= link_to 'Show', @sale, class:'button2' %> 
<%= link_to 'Back', sales_path, class:'button2' %>
</div>

<% end %>

final_project2/app/views/sales/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="head" style="text-align: center;">Sales</h1>

<h2 class="text" style="text-align: center;">Product IDs:</h2>
  <table class="table">
  <thead class="th2" style="text-align: center;">
    <tr>
      <th>ID</th>
      <th>Product</th>
      <th>Description</th>
      <th>Category</th>
      <th>Image</th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |pro|%>
    <div>
      <tr>
        <td class="td"><%= pro.id%></td>
        <td class="td" ><%= pro.name%></td>
        <td class="td"><%= pro.description%></td>
        <td class="td"><%= pro.category.name%></td>
        <td class = "td"><%= image_tag pro.avatar.url(:medium)%></td>
      </tr>
    </div>
  <% end %>
  </tbody>
</table>
  <br>
<table class="table">
  <thead class="th2">
    <tr>
      <th>Seller</th>
      <th>Buyer</th>
      <th>Product</th>
      <th>Price</th>
      <th>Remarks</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sales.each do |sale| %>
      <tr>
        <td class="td"><%= sale.seller.first_name %> <%= sale.seller.last_name %></td>
        <% if !sale.buyer_id.nil?%>
          <%@buyers.each do |buy| %>
              <% if sale.buyer_id == buy.id %>
                <td class="td"><%= buy.first_name %> <%= buy.last_name %></td>
              <%end%>
          <%end%>
        <% else %>
          <td class="td">no buyer</td>
        <%end%>
        <td class="td"><%= sale.product_id%></td>
        <td class="td"><%= sale.price %></td>
        <td class="td"><%= sale.remarks %></td>
        <td class="td"><%= link_to 'Show', sale %></td>
        <% if seller_logged_in? && (current_user == sale.seller) || (current_user.admin?) %>
        <td class="td"><%= link_to 'Edit', edit_sale_path(sale) %></td>
        <td class="td"><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end%>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if seller_logged_in? %>
<div style="text-align: center;">
  <%= link_to 'New Sale', new_sale_path, class:'button2' %>
</div>

<% end %>

final_project2/app/views/sales/new.html.erb
<div class="sign">
	<h1 class="head">New Sale</h1>
</div>


<%= render 'form', sale: @sale %>
<br>
<div class="sign">
<%= link_to 'Back', sales_path, class:'button2' %>	
</div>

final_project2/app/views/sales/own.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>My Products</title>
</head>
<body>
	<div class="sign">
		<h2 class="head" style="text-align: center;">FOR SALE:</h2>
	</div>

	<table class="table">
  		<thead class="th2">
  			<tr>
  				<th>Seller</th>
				<th>Buyer</th>
				<th>Product</th>
				<th>Price</th>
				<th>Remarks</th>
				<th colspan="3"></th>
			</tr>
		</thead>
		<tbody>  
			<tr>
				<% @sales.each do |sale| %>
					<% if (seller_logged_in? && (current_user == sale.seller)) && sale.buyer_id.nil? %>
				   		<td class="td"><%= sale.seller.first_name %> <%= sale.seller.last_name %></td>
					    <td class="td">no buyer</td>
						<td class="td"><%= sale.product.name %></td>
						<td class="td"><%= sale.price %></td>
						<td class="td"><%= sale.remarks %></td>
						<td class = "td"><%= image_tag sale.product.avatar.url(:medium)%></td>
						<td class="td"><%= link_to 'Show', sale %></td>
						<td class="td"><%= link_to 'Edit', edit_sale_path(sale) %></td>
						<td class="td"><%= link_to 'Destroy', sale, method: :delete, data: { confirm: 'Are you sure?' } %></td>
			</tr>
					<% end %>
				<% end %>
  		</tbody>
  	</table>
<div class="sign">
		<h2 class="head" style="text-align: center;">SOLD:</h2>
	</div>
	<% @sales.each do |sale| %>
	<% if seller_logged_in? && (current_user == sale.seller) %>
		<% if !sale.buyer.nil?%>
		<table class="table">
  			<thead class="th2">
  				<tr>
  					<th>Seller</th>
				    <th>Buyer</th>
				    <th>Product</th>
				    <th>Price</th>
				    <th>Remarks</th>
				    <th colspan="3"></th>
				</tr>
			</thead>
			<tbody>  
				<tr>
				    <td class="td"><%= sale.seller.first_name %><%= sale.seller.last_name %></td>
					<td class="td"><%= sale.buyer.first_name %><%= sale.buyer.last_name %></td>
					<td class="td"><%= sale.product.name %></td>
					<td class="td"><%= sale.price %></td>
					<td class="td"><%= sale.remarks %></td>
					<td class = "td"><%= image_tag sale.product.avatar.url(:medium)%></td>
					<td class="td"><%= link_to 'Show', sale %></td>
				</tr>
  			</tbody>
  		<%end%>
  	<% end %>
<% end %>
</table>

</body>
</html>

final_project2/app/views/sales/show.html.erb
<p class="sign" id="notice"><%= notice %></p>
<img class="edit" src="/edit/edit.jpg">
<br>
<br>

<p class="sign">
  <strong class="text">Seller:</strong>
  <%= @sale.seller.first_name %>
  <%= @sale.seller.last_name %>
</p>
<p class="sign">
  <strong class="text">Buyer:</strong>
  <% if !@sale.buyer_id.nil?%>
    <%= @sale.buyer.first_name %>
    <%= @sale.buyer.last_name %>
  <% else %>
    no buyer
  <%end%>
</p>
  

<p class="sign">
  <strong class="text">Product:</strong>
  <%= @sale.product.name %>
</p>

<p class="sign">
  <strong class="text">Price:</strong>
  <%= @sale.price %>
</p>

<p class="sign">
  <strong class="text">Remarks:</strong>
  <%= @sale.remarks %>
</p>

<p class = "sign">
  <strong class = "text">Image:</strong>
  <%= image_tag @sale.product.avatar.url(:medium)%>
</p>

<% if !buyer_logged_in? %>
<br>
<div class="sign">
  <%= link_to 'Edit', edit_sale_path(@sale), class:'button2' %> 
<%= link_to 'Back', sales_path, class:'button2' %>
</div>
<% else%>
<div class="sign">
      <%= link_to 'Back', mypurchases_path, class:'button2'  %>
</div>

<% end %>